### PR TITLE
theMostAnoyingPrInMyLife

### PR DESCRIPTION
**Pull request by FBartos**
fixes: https://github.com/jasp-stats/INTERNAL-jasp/issues/1988
fixes: https://github.com/jasp-stats/INTERNAL-jasp/issues/1989

### CODE REVIEW

**Comment by FBartos** [comment]
Any idea why the plots unit tests fail on macOS and Windows @vandenman @Kucharssim ?

Also, how should I go about renaming the `ColumnLayout` and `ComponentsList` in https://github.com/jasp-stats/jaspLearnBayes/blob/master/inst/qml/LSbinomialestimation.qml#L57-L150 and https://github.com/jasp-stats/jaspLearnBayes/blob/master/inst/qml/LSbinomialtesting.qml#L58-L170 ?

**Comment by FBartos** [comment]
Also, I found a bug in `Binomial Estimation` that puzzles me. This happens on initialization (to open the `Sequential Analysis` tab, one must to change the `Input Type` to `Data Sequence`:
image

The default values and limits seems to be set correctly? Once I get the double field into focus, the bug disapears.
```
DoubleField
{
	enabled:			plotsIterativeInterval.checked
	name:				"sequentialAnalysisIntervalEstimatePlotLower"
	label:				qsTr("Lower")
	id:					plotsIterativeIntervalLower
	fieldWidth:			50
	defaultValue:		analysisType === "binomial" ? 0.25 : -1
	min:				analysisType === "binomial" ? 0    : -9999999999
	max:				plotsIterativeIntervalUpper.value
	inclusive:			JASP.MinOnly
}

DoubleField
{
	enabled:			plotsIterativeInterval.checked
	name:				"plotsIterativeIntervalUpper"
	label:				qsTr("Upper")
	id:					plotsIterativeIntervalUpper
	fieldWidth:			50
	defaultValue:		analysisType === "binomial" ? 0.75 : 1
	min:				plotsIterativeIntervalLower.value
	max:				analysisType === "binomial" ? 1    : 9999999999
	inclusive: 			JASP.MaxOnly
}
```

**Comment by EJWagenmakers** [comment]
I think this is the same one as https://github.com/jasp-stats/INTERNAL-jasp/issues/2158

**Comment by FBartos** [comment]
Ah, I deleted the comment after I accidentally fixed it by renaming one of the options and did not notice EJ's comment
interestingly, it seems like the qml was accessing the `name` instead of the `id` property...
fixes: https://github.com/jasp-stats/INTERNAL-jasp/issues/2158

**Pull request merged**
