### PR TITLE
Update test plots

### PR DESCRIPTION
**Pull request by Kucharssim**
After this is merged, @FBartos can rebase his https://github.com/jasp-stats/jaspLearnBayes/pull/119 so that the tests pass there as well

### CODE REVIEW

**Comment by vandenman** [comment]
2 tests fail on windows though. Any idea why?

**Comment by Kucharssim** [comment]
Hm yeah I am not sure, and since I don't have windows I cannot check...

**Comment by Kucharssim** [comment]
Well at least Mac and Ubuntu passed, should I just skip the failing plots on windows? I am not sure what to do otherwise

**Comment by vandenman** [comment]
> should I just skip the failing plots on windows? 

sure, perhaps @FBartos can take another look at those specific failures on windows?

**Comment by FBartos** [comment]
I looked through a couple of plots and I don't see ANY changes in them, yet they trigger unit tests. Moreover, when I accept a change on the first figure, RStudio freezes....

**Comment by vandenman** [comment]
> I don't see ANY changes in them

The changes are almost all like this:

image

so essentially invisible and meaningless. See [here](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linecap#example) for en example of what stroke-linecap does.

A bit annoying that you can't update the test figures though. Are you up to date with all your dependencies? You can also run the shiny app in the browsers if I remember correctly.

**Comment by FBartos** [comment]
hmm, now I was able to accept the changes to the figures, let me update them and push them into this PR then?

**Comment by Kucharssim** [comment]
> hmm, now I was able to accept the changes to the figures, let me update them and push them into this PR then?

What are the differences though? will it in turn break the tests for Mac and Linux? :D

**Comment by Kucharssim** [comment]
@FBartos do you want to push the updates here? Otherwise if @vandenman does not object I would merge this

**Comment by FBartos** [comment]
You should probably just merge it and I can create a different PR? I'm also not sure whether the PR will ruin the other tests?

**Comment by Kucharssim** [comment]
> You should probably just merge it and I can create a different PR? 

@vandenman is it ok to merge as it, then?

> I'm also not sure whether the PR will ruin the other tests?

It probably would if it's really an issue that the plots are different on different platforms. Note that if that's the case we could also test the same output on different platforms separately (like here: https://github.com/jasp-stats/jaspProphet/blob/ff711e5d9fbea9c2fba3f95efae7712bc8393491/tests/testthat/test-prophet.R#L185). It would just require from you to add the skipping logic + add the windows generated plots to the test files.

**Comment by vandenman** [comment]
Sure just merge it then

**Pull request merged**
